# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:


# config/services.yaml

services:
  _defaults:
    autowire: true      # Injection automatique des dépendances
    autoconfigure: true # Enregistrement automatique des services

  App\:
        resource: '../src/'

  # Enregistrement du service MenuStatsService
  App\Service\MenuStatsService:
    arguments:
      $mongoUri: '%env(MONGODB_URI)%'
    public: true

  # EventListener pour la synchronisation automatique
  App\EventListener\CommandeListener:
    arguments:
      - '@App\Service\MenuStatsService'
      - '@App\Repository\AvisRepository'
    tags:
      - { name: doctrine.event_listener, event: postPersist, priority: 500 }
      - { name: doctrine.event_listener, event: postUpdate, priority: 500 }
      - { name: doctrine.event_listener, event: postRemove, priority: 500 }

  # Command pour la synchronisation en batch
  App\Command\SyncMenuStatsCommand:
    arguments:
      - '@App\Repository\MenuRepository'
      - '@App\Service\MenuStatsService'
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: console.command }

  # Controller Admin avec injection du service
  App\Controller\Admin\DashboardController:
    arguments:
      - '@App\Service\MenuStatsService'